#!/bin/bash
# assign variables

ACTION=${1}
version=1.0.1

function create_file() {
touch "${1}-12345"
}

function delete_file() {
rm "${1}-12345"
}

function show_version() {
echo "$version"
}

function display_help() {

cat << EOF
Usage: ${0} {-c|--create|-h|--help|-d|--delete|-v|--version} <filename>
OPTIONS:
-c | --create Create a new file
-h | --help Display the command help
-d | --delete Delete a file
-v | --version Show the version of the script
Examples:
Create a new file:
$ ${0} -c foo.txt
Display help:
$ ${0} -h
Delete a file
$ ${0} -d foo-12345.txt
Show the version of the script
$ ${0} -v 
EOF

}
case "$ACTION" in
-h|--help)
display_help
;;

-c|--create)
create_file "${2:-server}"
;;

-d|--delete)
delete_file "${2:-server}"
;;

-v|--version)
show_version
;;
*)
echo "Usage ${0} {-c|-h|-d|-v}"
exit 1
esac
